### PR TITLE
Can Change delegate file js

### PR DESCRIPTION
**Pull request by erkurn**
1. Can change default delegrate js, with this function you can adding puppeteer extra plugin or another package
2. add AppServiceProvider for publishing default delegatejs `PuppeteerConnectionDelegate.js`. i confusing, the service provider not auto discovery, so you must add manual to `config/app.app`

### CODE REVIEW

**Comment by spekulatius** [comment]
Hey @erkurn 

Thanks for you contribution. The project is not actually closely related to Laravel - more pure PHP/JS. Hence the missing service provider. Not so sure if this something we are keen to introduce atm.

The option to have a custom delegation js sounds good to me.

Whats your take @nesk ?

Cheeers,
Peter

**Comment by erkurn** [comment]
Hey @spekulatius ow, okay, so auto discovery can i take out. but custom delegation js i think is good

**Comment by spekulatius** [comment]
Let's see what @nesk feels about it :+1:

**Comment by nesk** [comment]
Thank you for your PR @erkurn. Unfortunately, I can't merge this but I can explain why. What you're trying to do here is opening the code internals of PuPHPeteer to add some extensions to it. This is unmanageable for us because it could easily introduce breaking changes on small updates, and you wouldn't be happy about that.

However, what I can propose you is to provide the delegation file you have created to fit your use case and explain us what plugins you want to install and how. Maybe we could create a public API for PuPHPeteer to allow you to use plugins without opening the code internals.

**Pull request closed without merging**
