### PR TITLE
Suggestions to tweak before integrating into main

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @nesk 

as discussed here the minor tweaks before bringing this back in. The last commit contains the result of running it, if this causes issues we can take it out easily. 

Otherwise looks good!

Cheers,
Peter

### CODE REVIEW

**Comment by nesk** [comment]
Thank you so much for taking time reviewing this. You saw nothing weird in the generated phpdoc?

**Comment by spekulatius** [comment]
I looked only over a few and the changes from re-running it. Anything in particular to look at @nesk?

**Comment by nesk** [comment]
I'm merging this PR because its valid. However, as you know, we will have to fix the documentation generator first.

**Comment by spekulatius** [comment]
Yeah :/ That's going to be piece of work too...

**Pull request merged**
